package main

//
// a MR application you need to develop
// go build -buildmode=plugin credit.go
//

import (
	"cs350/mr"
	"strconv"
	"strings"
)

// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
func Map(filename string, contents string) []mr.KeyValue {
	// your inplementation here
	lines := strings.Split(contents, "\n")

	kva := []mr.KeyValue{}
	for _, line := range lines {
		data := strings.Split(line, ",")
		if len(data) != 4 {
			continue
		}
		agency := data[1]
		year, _ := strconv.Atoi(data[2])
		creditScore, _ := strconv.Atoi(data[3])

		if year == 2023 && creditScore > 400 {
			kv := mr.KeyValue{agency, "1"}
			kva = append(kva, kv)
		}
	}
	return kva
}

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
func Reduce(key string, values []string) string {
	// your inplementation here
	print(strconv.Itoa(len(values)))
	return strconv.Itoa(len(values))
}
